### ISSUE TITLE
反馈个编译不过的问题。win10

### ISSUE THREAD

**Issue by hhhaiai** [virjar/zelda#1]
Build command failed.
Error while executing process D:\tools\dev\studio_sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\sanbo\Desktop\zelda\zelda-engine\.externalNativeBuild\cmake\debug\armeabi-v7a --target zeldanative}
[1/3] Building CXX object CMakeFiles/zeldanative.dir/Jni/Helper.cpp.o
[2/3] Building CXX object CMakeFiles/zeldanative.dir/Foundation/SandboxFs.cpp.o
FAILED: D:\tools\dev\ndk\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  -target armv7-none-linux-androideabi -gcc-toolchain D:/tools/dev/ndk/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/tools/dev/ndk/android-ndk-r12b/platforms/android-21/arch-arm  -DCORE_SO_NAME=\"zeldanative\" -DNATIVE_TAG_NAME=\"Zelda\" -DZELDA_BUILD_TYPE_DEBUG -Dzeldanative_EXPORTS -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/Foundation -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/Jni -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/. -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti  -std=c++0x -funwind-tables -g -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/zeldanative.dir/Jni/Helper.cpp.o -MF CMakeFiles\zeldanative.dir\Jni\Helper.cpp.o.d -o CMakeFiles/zeldanative.dir/Jni/Helper.cpp.o -c C:\Users\sanbo\Desktop\zelda\zelda-engine\src\main\cpp\Jni\Helper.cpp
C:\Users\sanbo\Desktop\zelda\zelda-engine\src\main\cpp\Jni\Helper.cpp:3:10: fatal error: 'bits/sysconf.h' file not found

#include <bits/sysconf.h>

         ^

1 error generated.

FAILED: D:\tools\dev\ndk\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  -target armv7-none-linux-androideabi -gcc-toolchain D:/tools/dev/ndk/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/tools/dev/ndk/android-ndk-r12b/platforms/android-21/arch-arm  -DCORE_SO_NAME=\"zeldanative\" -DNATIVE_TAG_NAME=\"Zelda\" -DZELDA_BUILD_TYPE_DEBUG -Dzeldanative_EXPORTS -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/Foundation -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/Jni -IC:/Users/sanbo/Desktop/zelda/zelda-engine/src/main/cpp/. -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem D:/tools/dev/ndk/android-ndk-r12b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti  -std=c++0x -funwind-tables -g -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/zeldanative.dir/Foundation/SandboxFs.cpp.o -MF CMakeFiles\zeldanative.dir\Foundation\SandboxFs.cpp.o.d -o CMakeFiles/zeldanative.dir/Foundation/SandboxFs.cpp.o -c C:\Users\sanbo\Desktop\zelda\zelda-engine\src\main\cpp\Foundation\SandboxFs.cpp
C:\Users\sanbo\Desktop\zelda\zelda-engine\src\main\cpp\Foundation\SandboxFs.cpp:2:10: fatal error: '__hash_table' file not found

#include <__hash_table>

         ^

1 error generated.

ninja: build stopped: subcommand failed.

**Comment by virjar** [comment]
hello ,你的ndk版本看起来太低了。
android-ndk-r12b

建议至少在ndk-r18以上

**Comment by hhhaiai** [comment]
本地的编译环境，各种ndk都有
